# Generated by Django 2.2.4 on 2019-09-15 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20190915_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='challenge',
            field=models.CharField(choices=[('M', 'Metro'), ('B', 'Bike'), ('W', 'Walk')], default='M', max_length=10),
        ),
    ]
