# Generated by Django 2.2.4 on 2019-09-15 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20190915_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='challenge',
            field=models.CharField(choices=[('Metro', 'Metro'), ('Bike', 'Bike'), ('Walk', 'Walk')], default='Metro', max_length=10),
        ),
    ]
