# Generated by Django 2.2.3 on 2019-09-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20190915_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='points',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
