# Generated by Django 2.2.4 on 2019-09-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_post_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='points',
            field=models.IntegerField(default=10),
        ),
    ]
