# Generated by Django 2.1.5 on 2019-09-16 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20190916_1709'),
        ('main_app', '0012_auto_20190916_1734'),
    ]

    operations = [
    ]
